---
- name: Copiar archivo y reiniciar nginx en hosts Linux
  hosts: all
  become: yes 
  tasks:
    - name: Respaldo index
      become: yes
      ansible.builtin.copy:
        src: /var/www/beonit/html/dist/index.html
        dest: /var/www/beonit/html/dist/pivot.html
        owner: usrcontroller
        group: usrcontroller
        mode: '0777'

    - name: cambio de Mantenimiento a Principal
      become: yes
      copy:
        src: /var/www/beonit/html/dist/mantenimiento.html
        dest: /var/www/beonit/html/dist/index.php

    - name: Respaldo Mantenimiento
      become: yes
      copy:
        dest: /var/www/beonit/html/dist/pivot.html
        src: /var/www/beonit/html/dist/mantenimiento.html
        
    - name: Reiniciar nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
