---
- name: Copiar archivo y reiniciar nginx en hosts Linux
  hosts: all
  become: yes 
  tasks:
    - name: Respaldo index
      become: yes
      command: mv /home/usrcontroller/pagina/index.html /home/usrcontroller/pagina/pivot.html

    - name: cambio de Mantenimiento a Principal
      become: yes
      copy:
        src: /var/www/beonit/html/dist/mantenimiento.html
        dest: /var/www/beonit/html/dist/index.html

    - name: Respaldo Mantenimiento
      become: yes
      copy:
        dest: /var/www/beonit/html/dist/pivot.html
        src: /var/www/beonit/html/dist/mantenimiento.html
        
    - name: Reiniciar nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
