---
- hosts: all
  become: yes
  
  vars:
    zabbix_server_repo: 'https://repo.zabbix.com/zabbix/6.5/ubuntu'
  tasks:  
    - name: Agregar repositorio de Zabbix
      apt_repository:
        repo: "{{ zabbix_server_repo }}"
        state: present
        update_cache: yes
    
    - name: Instalar el agente de Zabbix
      apt:
        name: zabbix-agent
        state: present
