---
- name: Bloquear una dirección IP específica con UFW
  hosts: all
  become: yes

  tasks:
    - name: Instalar UFW
      apt:
        name: ufw
        state: present

    - name: Habilitar UFW
      command: ufw enable

    - name: Bloquear tráfico ICMP desde una dirección IP específica
      community.general.ufw:
        rule: deny
        proto: http
        src: "{{ ip_a_bloquear }}"

    - name: Recargar UFW para aplicar cambios
      command: ufw reload
