---
- name: Bloquear una dirección IP específica con UFW
  hosts: all
  become: yes

  tasks:
    - name: Instalar UFW
      apt:
        name: ufw
        state: present

    - name: Habilitar UFW
      command: ufw enable
      args:
        creates: /etc/ufw/ufw.conf
        
    - name: Bloquear tráfico ICMP desde una dirección IP específica
      community.general.ufw:
        rule: deny
        port: 80
        proto: tcp
        src: "{{ ip_a_bloquear }}"

    - name: Recargar UFW para aplicar cambios
      command: ufw reload
