---
- name: Deshabilitar acceso de usuario en servidores Linux
  hosts: all
  become: yes
  tasks:
    - name: Deshabilitar el inicio de sesión del usuario
      user:
        name: {{ user_name }}
        shell: /sbin/nologin

    - name: Opcionalmente, deshabilitar la contraseña del usuario
      user:
        name: {{ user_name }}
        password_lock: yes
